version: "3.3"
services:
    # front:
    #   build:
    #       dockerfile: Dockerfile
    #       context: ./frontend
    #   env_file:
    #       - .env
    #   depends_on: 
    #       - api
    #   ports:
    #       - "3000:3000"

    api:
        build:
            dockerfile: Dockerfile
            context: ./backend
        depends_on: 
            - postgres
        env_file:
          - .env
        environment:
            SECRET_KEY: "randomString"
            DATABASE_URL: postgres://admin:admin@postgres:5432/db
            NODE_ENV: development
            PORT: 5000
        volumes:
          - "./backend/app/profil_pic/:/user/src/app/uploads/profilpic"
        ports:
            - "5000:5000"

    postgres:
        image: postgres:10.4
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: db
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
        ports:
          - "5050:80"
volumes:
    pgdata: